---
- name: Install required packages
  ansible.builtin.yum:
    name:
      - emacs-filesystem
      - less
      - libsecret
      - openssh-server
      - openssh-clients
      - openssl-devel
      - pcre2
      - readline-devel
      - unzip
    state: present

- name: Install perl(Term::ReadKey)
  ansible.builtin.yum:
    name:
      - perl-TermReadKey
    state: present

- name: Install perl(Error)
  ansible.builtin.yum:
    name:
      - perl-Error
    state: present

- name: Install IUS yum repository
  ansible.builtin.yum:
    name: 'https://repo.ius.io/ius-release-el7.rpm'
    state: present

- name: Install Git
  ansible.builtin.yum:
    name: git
    disablerepo: "base,epel,extras,updates"
    enablerepo: ius
    state: present
