---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check whether Git is installed
      ansible.builtin.shell: |
        git --version
      register: GIT_INSTALLED
      changed_when: false

    - name: Make sure Git is installed
      ansible.builtin.debug:
        var: GIT_INSTALLED

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
