---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check whether Git is installed
      ansible.builtin.command: git --version  # noqa command-instead-of-module
      register: git_installed
      changed_when: false

    - name: Make sure Git is installed
      ansible.builtin.debug:
        var: git_installed

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
